version: "3.9"

services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env # ルートに配置した秘密キー等
    environment:
      PYTHONUNBUFFERED: "1"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_APP_ENV=${VITE_APP_ENV}
      - VITE_API_ENDPOINT=${VITE_API_ENDPOINT}
    env_file:
      - .env

volumes:
  node_modules:


