name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd backend
        python -m pytest tests/ -v

  # Railway GitHub Integrationを使用する場合は、このdeployジョブは不要です
  # RailwayダッシュボードでGitHubリポジトリを連携してください
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - uses: actions/checkout@v3
  #   
  #   - name: Deploy to Railway using CLI
  #     env:
  #       RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  #     run: |
  #       # Railway CLIをインストール
  #       npm install -g @railway/cli
  #       
  #       # Railwayにログイン（トークンを使用）
  #       railway login --token $RAILWAY_TOKEN
  #       
  #       # プロジェクトをデプロイ
  #       railway up